rdp: Support FreeRDP-1.2.0-beta1-android9
Fix build errors.

  CC       access/librdp_plugin_la-rdp.lo
access/rdp.c: In function ‘Open’:
access/rdp.c:431:5: error: implicit declaration of function ‘freerdp_channels_global_init’ [-Werror=implicit-function-declaration]
     freerdp_channels_global_init();
     ^
access/rdp.c: In function ‘Close’:
access/rdp.c:507:5: error: implicit declaration of function ‘freerdp_channels_global_uninit’ [-Werror=implicit-function-declaration]
     freerdp_channels_global_uninit();
     ^

freerdp channels global functions were removed from FreeRDP repository
in commit 2a82684521dc8b23ae92e284e866227e5194a7bb.

commit 2a82684521dc8b23ae92e284e866227e5194a7bb
Author: Marc-André Moreau <marcandre.moreau@gmail.com>
Date:   Wed Jun 11 16:27:31 2014 -0400

    channels: cleanup unused freerdp channels global functions

Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>
(cherry picked from commit 5c07f87a773153c128b3a771ed61e7915cd8fe18)
Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>