dvdnav: fix compilation on OS/2
-----
access/dvdnav.c: In function 'ProbeDVD':
access/dvdnav.c:1469:6: error: implicit declaration of function 'read' [-Werror=implicit-function-declaration]
      || read( fd, iso_dsc, sizeof (iso_dsc) ) < (int)sizeof (iso_dsc)
      ^
access/dvdnav.c:1481:5: error: implicit declaration of function 'close' [-Werror=implicit-function-declaration]
     close( fd );
     ^
-----

Signed-off-by: Rémi Denis-Courmont <remi@remlab.net>
(cherry picked from commit 4bcf8bd7ae0e00e9e1a55fce2e559a5dc465a29f)
Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>