video_splliter: Add XCB flags for panoramix.
This patch fixes this build error.

video_splitter/.libs/libpanoramix_plugin_la-panoramix.o: In function `CountMonitors':
modules/video_splitter/panoramix.c:352: undefined reference to `xcb_connect'
modules/video_splitter/panoramix.c:354: undefined reference to `xcb_connection_has_error'
modules/video_splitter/panoramix.c:357: undefined reference to `xcb_get_setup'
modules/video_splitter/panoramix.c:359: undefined reference to `xcb_setup_roots_iterator'
modules/video_splitter/panoramix.c:360: undefined reference to `xcb_screen_next'
modules/video_splitter/panoramix.c:407: undefined reference to `xcb_disconnect'
modules/video_splitter/panoramix.c:407: undefined reference to `xcb_disconnect'
modules/video_splitter/panoramix.c:407: undefined reference to `xcb_disconnect'

Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>
(cherry picked from commit a854dc7108cdb70b5f58a1232868c74ad3620c99)
Signed-off-by: Jean-Baptiste Kempf <jb@videolan.org>